apiVersion: v1
kind: Service
metadata:
  name: primes-new
spec:
  type: NodePort 
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
    
  selector:
    app: primes-new

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primes-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primes-new
  template:
    metadata:
      labels:
        app: primes-new
    spec:
      containers:
        - name: primes-new
          image: stivenzxy/primes-new-ms:1.0
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_DB
              value: primesdb
            - name: POSTGRES_USER
              value: primesuser
            - name: POSTGRES_PASSWORD
              value: primespass
