apiVersion: v1
kind: Service
metadata:
  name: primes-result
spec:
  type: NodePort 
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 30002
  selector:
    app: primes-result

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primes-result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primes-result
  template:
    metadata:
      labels:
        app: primes-result
    spec:
      containers:
        - name: primes-result
          image: stivenzxy/primes-result-ms:1.0
          ports:
            - containerPort: 5002
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_DB
              value: primesdb
            - name: POSTGRES_USER
              value: primesuser
            - name: POSTGRES_PASSWORD
              value: primespass
