apiVersion: v1
kind: Service
metadata:
  name: status-service
spec:
  selector:
    app: status-service
  ports:
    - port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-service
  template:
    metadata:
      labels:
        app: status-service
    spec:
      containers:
        - name: status-service
          image: primes/status-service:latest
          ports:
            - containerPort: 8001
