apiVersion: v1
kind: Service
metadata:
  name: primes-status
spec:
  type: NodePort 
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30001
  selector:
    app: primes-status

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primes-status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primes-status
  template:
    metadata:
      labels:
        app: primes-status
    spec:
      containers:
        - name: primes-status
          image: vanessalopezt/primes-status:1.0
          ports:
            - containerPort: 5001
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_DB
              value: primesdb
            - name: POSTGRES_USER
              value: primesuser
            - name: POSTGRES_PASSWORD
              value: primespass
