apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  selector:
    app: result-service
  ports:
    - port: 8002
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-service
  template:
    metadata:
      labels:
        app: result-service
    spec:
      containers:
        - name: result-service
          image: primes/result-service:latest
          ports:
            - containerPort: 8002
