apiVersion: apps/v1
kind: Deployment
metadata:
  name: primes-workers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: primes-worker
  template:
    metadata:
      labels:
        app: primes-worker
    spec:
      containers:
        - name: primes-worker
          image: vanessalopezt/primes-worker:1.0
          env:
            - name: REDIS_HOST
              value: redis
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_DB
              value: primesdb
            - name: POSTGRES_USER
              value: primesuser
            - name: POSTGRES_PASSWORD
              value: primespass
